add: manual checkpoints
homerchen19/use-undo pull request #36
Opened 2022-03-10 16:54 UTC by Robokishan

Right now i am using this package with list of form. the problem is if we change input value, then also. history is getting recorded. i have a delete button. so I need a manual control over recording history. other packages have added manual checkpoint option. but those are required to use reducer. but in this package it is very easy so I have also added manual checkpoints in this also

if using manual checkpoint option then we need to pass `setInputList(list, true); ` true to record value in history.
other wise it is ignored. if we don't use manual checkpoint then it will work as expected

2022-03-11 14:40 UTC, homerchen19 commented
Hi @Robokishan I think this is a good feature.
Could you write some unit tests for it? `README` needs to be updated too.

2022-03-11 14:41 UTC, homerchen19 requested changes

2022-03-11 14:41 UTC, homerchen19 commented on index.ts
> +          past: isNewCheckpoint == false ? past : [...past, present],
Why don't we use `===`?

2022-03-14 06:24 UTC, Robokishan commented on index.ts
> +          past: isNewCheckpoint == false ? past : [...past, present],
Thanks will do that

2022-03-14 06:24 UTC, Robokishan commented
> Hi @Robokishan I think this is a good feature. Could you write some unit tests for it? `README` needs to be updated too.

Sure will do that give me some time

2022-03-23 07:08 UTC, Robokishan commented
@homerchen19 Can you please re review ?

2022-04-12 07:07 UTC, Robokishan commented
@homerchen19 any update please ?

2022-04-12 14:38 UTC, homerchen19 approved these changes

2022-04-12 14:38 UTC, merged